const router = require('express')?.Router();
const { getAutoGeneratedCaptions, getTranslatedCaptions } = require('../controllers/vimeo');

// Vimeo routes
router.post('/auto-generated-captions', getAutoGeneratedCaptions);

router.get('/translated-captions', getTranslatedCaptions); // Lambda function

module.exports = router;